---
version: 0.2.0

trigger: default

keywords:
  # dyff related comments
  - name: run-dyff
    value: '^\/run-dyff$'

  # Importer related comments
  - name: run-importer-update
    value: '^\/run-importer-update$'
  - name: run-importer-update-file
    value: '^\/run-importer-update (.+)$'
