commonAnnotation:
  prometheus:
    # == export: prometheus-annotation / begin ==
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
    # == export: prometheus-annotation / end ==

commonArgs:
  # == export: common-args / begin ==
  - --watch-all-namespaces
  - --log-level=info
  - --log-encoding=json
  - --enable-leader-election
  # == export: common-args / end ==

commonEnvs:
  # == export: common-envs / begin ==
  env:
  - name: RUNTIME_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  # == export: common-envs / end ==

resource-and-probes:
  # == export: probe-and-resource / begin ==
  name: manager
  imagePullPolicy: IfNotPresent
  livenessProbe:
    httpGet:
      path: /healthz
      port: healthz
  readinessProbe:
    httpGet:
      path: /readyz
      port: healthz
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 64Mi
  # == export: probe-and-resource / end ==
