apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-svc
spec:
  template:
    spec:
      containers:
        - name: color-svc
          env:
            - name: DELAY_DURATION_MILLISECOND
              value: "0"
