---
apiVersion: v1
kind: Service
metadata:
  name: color-svc
  labels:
    app.kubernetes.io/name: color-svc
spec:
  ports:
    - name: http
      port: 8800
      targetPort: 8800
  selector:
    app.kubernetes.io/name: color-svc
