---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolkit-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: toolkit-alpine
      version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: toolkit-alpine
        version: v1
    spec:
      serviceAccountName: toolkit-alpine
      containers:
        - image: docker.io/rytswd/toolkit-alpine:0.1.1
          name: toolkit-alpine
          command: ["/bin/sleep", "3650d"]
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 30m
              memory: 30Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolkit-alpine-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: toolkit-alpine
      version: v2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: toolkit-alpine
        version: v2
    spec:
      serviceAccountName: toolkit-alpine
      containers:
        - image: docker.io/rytswd/toolkit-alpine:0.2.x # This does not exist
          name: toolkit-alpine
          command: ["/bin/sleep", "3650d"]
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 30m
              memory: 30Mi
