---
name: CI - Kustomize Build
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - kustomize/**

jobs:
  kustomize-build:
    name: Run kustomize build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install Kustomize
        run: brew install kustomize

      - name: Run kustomize build
        run: |
          while IFS= read -r -d '' file
          do
            kustomize_dir=$(dirname "$file")
            echo "Running 'kustomize build' against '${kustomize_dir}' ..."
            kustomize build "$kustomize_dir" > /dev/null && echo '  Success!'
          done < <(find . -name 'kustomization.yaml' -print0)
